### ISSUE TITLE
handler.handle(UnitResponse.succeededSingleton()) causes exception.

### ISSUE THREAD

**Issue by happyyangyuan** [xiancloud/xian#37]
The exception
```
java.lang.IllegalArgumentException: Can not set an empty msgId. If you want to clear msgId of current context, use clear() instead.
```

**Comment by happyyangyuan** [comment]
Full stack trace:
```
java.lang.IllegalArgumentException: Can not set an empty msgId. If you want to clear msgId of current context, use clear() instead.
	at info.xiancloud.core.util.thread.MsgIdHolder.set(MsgIdHolder.java:60)
	at info.xiancloud.core.message.sender.local.AbstractLocalAsyncSender.lambda$null$1(AbstractLocalAsyncSender.java:71)
	at info.xiancloud.yy.succeeded_singleton.SucceededSingletonTestUnit.execute(SucceededSingletonTestUnit.java:25)
	at info.xiancloud.core.message.sender.local.AbstractLocalAsyncSender.lambda$asyncSend$2(AbstractLocalAsyncSender.java:70)
	at info.xiancloud.core.thread_pool.ThreadPoolManager.lambda$wrapRunnable$0(ThreadPoolManager.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by happyyangyuan** [comment]
succeededSingleton()返回的对象内的msgId为null，而local sender试图用它来初始化进行线程上下文导致抛出该异常。

解决方法是，在业务代码内避免使用succeededSingleton()方法，使用createSuccess()代替。

已经将succeededSingleton()方法置为`@deprecated`状态了。

**Comment by happyyangyuan** [comment]
补充复现测试代码：
```
test/ide_runtime_test/src/main/java/info/xiancloud/yy/succeeded_singleton/SucceededSingletonTestUnit.java
```
